"""Add produtos_matriz table

Revision ID: 940fa4394759
Revises: de4da57eb0d8
Create Date: 2026-10-09 14:32:37.973818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940fa4394759'
down_revision: Union[str, Sequence[str], None] = 'de4da57eb0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_matriz',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_origem', sa.String(), nullable=False),
    sa.Column('url_afiliada', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_matriz_id'), 'produtos_matriz', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_matriz_url_origem'), 'produtos_matriz', ['url_origem'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_matriz_url_origem'), table_name='produtos_matriz')
    op.drop_index(op.f('ix_produtos_matriz_id'), table_name='produtos_matriz')
    op.drop_table('produtos_matriz')
    # ### end Alembic commands ###
